

GET https://localhost:44330/api/participants HTTP/1.1

###

GET https://localhost:44330/api/participants/johndoe@email.com/sports HTTP/1.1

###
GET https://localhost:44330/api/participants/8ed7de7e-e9bc-4c9f-bbcb-a75a0dde59af
