

GET https://localhost:44330/api/sport/all HTTP/1.1

###

GET https://localhost:44330/api/sport/15ca1813-2dd1-47c6-8ce7-48857008bd5f HTTP/1.1

###
POST https://localhost:44330/api/sport HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiMDNiZjE1ZjgtYmRmMi00ZTE4LWIwNDgtOTlhNjViNWU0NDA2IiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJ1aWQiOiI2MmExNGUzYy1lZGFkLTQ5YTktOWNhYy00ZjkxZWUyZGMzNzAiLCJleHAiOjE2MTU4MTEyNTQsImlzcyI6IkFwcElkZW50aXR5IiwiYXVkIjoiQXBwSWRlbnRpdHlVc2VyIn0.Ef_l91PgPIkgXQhm2Nyp1mMRT1CSeKw4YuPJ1u4lVxk

{
  "name": "Football"
}

###

PUT https://localhost:44330/api/sport HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiMDNiZjE1ZjgtYmRmMi00ZTE4LWIwNDgtOTlhNjViNWU0NDA2IiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJ1aWQiOiI2MmExNGUzYy1lZGFkLTQ5YTktOWNhYy00ZjkxZWUyZGMzNzAiLCJleHAiOjE2MTU4MTEyNTQsImlzcyI6IkFwcElkZW50aXR5IiwiYXVkIjoiQXBwSWRlbnRpdHlVc2VyIn0.Ef_l91PgPIkgXQhm2Nyp1mMRT1CSeKw4YuPJ1u4lVxk

{
  "id": "26558f6b-ef1c-4367-1823-08d8e7a575cd",
  "name": "Football 1"
}

###
DELETE https://localhost:44330/api/sport/26558f6b-ef1c-4367-1823-08d8e7a575cd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiMDNiZjE1ZjgtYmRmMi00ZTE4LWIwNDgtOTlhNjViNWU0NDA2IiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJ1aWQiOiI2MmExNGUzYy1lZGFkLTQ5YTktOWNhYy00ZjkxZWUyZGMzNzAiLCJleHAiOjE2MTU4MTEyNTQsImlzcyI6IkFwcElkZW50aXR5IiwiYXVkIjoiQXBwSWRlbnRpdHlVc2VyIn0.Ef_l91PgPIkgXQhm2Nyp1mMRT1CSeKw4YuPJ1u4lVxk


