

GET https://localhost:44330/api/sport/all HTTP/1.1

###

GET https://localhost:44330/api/sport/allwithitems HTTP/1.1

###
GET https://localhost:44330/api/sport/4acfb92f-7c21-47de-8a4e-32f476e9bcfc HTTP/1.1

###
POST https://localhost:44330/api/sport HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiMjU0OTU5ZTEtYThkYi00MzBlLWI3ZmEtMGI5MjVmMDcxODk3IiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJ1aWQiOiI2MmExNGUzYy1lZGFkLTQ5YTktOWNhYy00ZjkxZWUyZGMzNzAiLCJleHAiOjE2MTU4MjQ0MjksImlzcyI6IkFwcElkZW50aXR5IiwiYXVkIjoiQXBwSWRlbnRpdHlVc2VyIn0.f_QE0Ob5xpkdPVILFSVOMsoJUp1gw65TgBXQGdt8HLc

{
  "name": "Football"
}

###

PUT https://localhost:44330/api/sport HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiMjU0OTU5ZTEtYThkYi00MzBlLWI3ZmEtMGI5MjVmMDcxODk3IiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJ1aWQiOiI2MmExNGUzYy1lZGFkLTQ5YTktOWNhYy00ZjkxZWUyZGMzNzAiLCJleHAiOjE2MTU4MjQ0MjksImlzcyI6IkFwcElkZW50aXR5IiwiYXVkIjoiQXBwSWRlbnRpdHlVc2VyIn0.f_QE0Ob5xpkdPVILFSVOMsoJUp1gw65TgBXQGdt8HLc

{
  "id": "8D3DFAA9-7E41-41FD-F3C7-08D8E7C41A91",
  "name": "Football 1"
}

###
DELETE https://localhost:44330/api/sport/8D3DFAA9-7E41-41FD-F3C7-08D8E7C41A91 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiMjU0OTU5ZTEtYThkYi00MzBlLWI3ZmEtMGI5MjVmMDcxODk3IiwiZW1haWwiOiJqb2huLmRvZUBlbWFpbC5jb20iLCJ1aWQiOiI2MmExNGUzYy1lZGFkLTQ5YTktOWNhYy00ZjkxZWUyZGMzNzAiLCJleHAiOjE2MTU4MjQ0MjksImlzcyI6IkFwcElkZW50aXR5IiwiYXVkIjoiQXBwSWRlbnRpdHlVc2VyIn0.f_QE0Ob5xpkdPVILFSVOMsoJUp1gw65TgBXQGdt8HLc


